openapi: 3.0.0
paths:
  /api/schedule/{workDayId}/slots:
    get:
      operationId: getTimeSlots
      parameters:
        - name: workDayId
          required: true
          in: path
          schema:
            type: number
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/GetSlotsSlotByWorkDayDto"
      summary: ""
      tags: &a1
        - Schedule
  /api/schedule:
    get:
      operationId: getMonthSchedule
      parameters:
        - name: year
          required: true
          in: query
          description: Year (2025–2100)
          schema:
            type: number
        - name: month
          required: true
          in: query
          description: Month (1–12)
          schema:
            type: number
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/GetMonthScheduleResponseDto"
      summary: ""
      tags: *a1
info:
  title: schedule API
  description: API for schedule module
  version: "1.0"
  contact: {}
tags:
  - name: schedule
    description: ""
servers: []
components:
  schemas:
    GetSlotsSlotByWorkDayDto:
      type: object
      properties:
        id:
          type: number
        time:
          type: string
        isAvailable:
          type: boolean
      required:
        - id
        - time
        - isAvailable
    GetMonthScheduleResponseDto:
      type: object
      properties:
        id:
          type: number
        date:
          type: string
          example: 2025-12-25
          format: date
        isAvailable:
          type: boolean
      required:
        - id
        - date
        - isAvailable
